name: FormAPI
main: jojoe77777\FormAPI\FormAPI
version: 1.4.0
api: 5.0.0
author: NurAzliYT

commands:
  fapi:
      description: "FormAPI Commands"
      permission: fapi.command

permissions:
  fapi.command:
      default: op
