--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/LEVANDA
build-by-default: true
branches:
- main
projects:
  FormAPI:
    path: FormAPI/
    icon: FormAPI/icon.png
  LevandaUI:
    path: LevandaUI/
...
