name: LevandaUI
main: LevandaUI\src\NurAzliYT\LevandaUI\LevandaUI.php
version: 1.0.0
api: 5.0.0
author: NurAzliYT
description: "Menu For Your Server"

commands:
  ui:
    description: "Open LevandaUI Menu"
    permission: levandaui.ui

permissions:
  levandaui.ui:
    default: true
    
  levandaui:
    description: "Open LevandaUI Menu"
    permission: levandaui.ui

permissions:
  levandaui.ui:
    default: true
